# Site settings
title: Hamlbars
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hamlbars (haml + handlebars) syntax highlighting support for Sublime Text 
  Editor.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://greplytix.github.io/Hamlbars"

# Build settings
markdown: kramdown

# Allowed ruby gem plugins
gems:
    - jekyll-sitemap
    - jekyll-redirect-from
